version: '3.4'

services:
  sps.signalrclient:
    image: ${DOCKER_REGISTRY-}spssignalrclient
    build:
      context: .
      dockerfile: SPS.SignalrClient/Dockerfile
    ports:
      - 62621:80
      - 62631:443

  sps.signalr.webmvcclient:
    image: ${DOCKER_REGISTRY-}spssignalrwebmvcclient
    build:
      context: .
      dockerfile: SPS.Signalr.WebMvcClient/Dockerfile
    ports:
      - 62622:80
      - 62632:443